### ISSUE TITLE
Set up Google Doc for whitepaper

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/openoceancloud#14]
@cgentemann and I just met and discussed how to structure the sprint. We are abandoning the GitHub idea as too much work and potentially not inclusive. Instead, we will just use a google doc. Once #7 is complete, we need to set up this Google Doc.

The doc URL will not be distributed openly. Instead, it will be accessible only to people who come to GatherTown.

Some issues to consider:
- The moderators will need to play an active role in keeping the doc from getting messed up and pointing contributors to the right place (e.g. this section needs more)
- There should be a clear way for contributors to add their name, affiliation, email, and ORCID
- To avoid groupthink, we should make it clear that contributions don't have to be all aligned or consistent with each other. Folks should feel free to add paragraphs that (politely) disagree with other contributions or propose new perspectives.

**Comment by cgentemann** [comment]
Gdoc created. We need to communicate the moderator role to moderators.
Added a link to sign-in to document/gather.town once arrived.
Added text to state contributions don't have to aligned/consistent.
