### ISSUE TITLE
Add Leslie's institutions to the Partners page

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/openoceancloud#4]
https://github.com/pangeo-data/openoceancloud/blob/main/content/homepage/partners.md

cc @leslie-yoc

**Comment by leslie-yoc** [comment]
As I am contracted to work with you all through Consortium for Ocean Leadership probably best to put that as my institution.

**Comment by leslie-yoc** [comment]
Alrighty, so I went in and edited the page to add information about COL and put Andrea and my names under there. I previewed it and it looked good so I committed the changes...but now I'm not seeing how I turn that into a pull request? Hopefully one of you can see that I did something in there?

**Comment by rabernat** [comment]
The difference here is that, with this repo, you have privileges to directly commit your changes, without a PR. 

![image](https://user-images.githubusercontent.com/1197350/131508719-a36953e5-fd8b-4453-867b-0feaebad4c3b.png)

You chose "commit directly", which resulted in commit 96608c838f37ef532cd8caa058cf723a62739785 going directly to the main branch.

**Comment by leslie-yoc** [comment]
Well crud...and it looks like for some reason the COL image didn't go through....I linked to it like the other images on the website, but it came through as a red flag for some reason on the live site (preview looks fine) :(  I'll get this fixed and then do a pull request.

**Comment by leslie-yoc** [comment]
Ok I see, the error coming up is from COL. It's a protection they put in place so no one can embed a COL images by linking to it directly from the COL site...soooo I just need to upload the COL logo to the OpenOceanCloud website and then I can link to that...except I don't know where to put the image...should I make an image folder? Thanks! And sorry for the slow ramp up here.

**Comment by rabernat** [comment]
Put the images in the `static` folder:

https://github.com/pangeo-data/openoceancloud/tree/main/static

> And sorry for the slow ramp up here.

Absolutely zero apologies necessary. The process is new and we are figuring it out as we good.

**Comment by cgentemann** [comment]
@leslie-yoc I updated the link using a webaddress I found on the COL website. It seems to work now. Can you approve please? thanks.

**Comment by leslie-yoc** [comment]
Hi @cgentemann, Still getting that error once it goes live. It looked fine for me in preview mode as well. It has to do with a plugin COL has on their site that essentially jams the signal of any of their images folks try to embed on their own site. Not sure why it doesn't come up in preview mode.

Is there an easy way to hit undo and go back to the other image I had in there? 

![Screen Shot 2021-09-01 at 2 52 01 PM](https://user-images.githubusercontent.com/82670547/131727514-2f452320-c4e5-4e0d-b669-b91f9984e2a7.png)

**Comment by cgentemann** [comment]
okay, changed back.... sorry!

**Comment by leslie-yoc** [comment]
No worries!!! I appreciate the help!!! Completely unforseen gremlin :)
