### ISSUE TITLE
Leslie's suggested updates to whitepaper page

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/openoceancloud#9]
Copied from email thread.

> That said, it would be good to put some more details on this webpage so folks have everything they need in this one spot. One way to do that would be to have 1 in your list be a more general - “Attend Our Virtual Community Brainstorm Session"
> 
> And then create a new section (above the intro section) with more details and the link to join GatherTown
> 
> Virtual Community Brainstorm Session - Sept. 15-17
> Join the global discussion to define the future of open-source cyberinfrastructure for ocean science through this 44-hour open, community brainstorming session. 
> 
> This is not your average meeting! This event is an asynchronous global sprint, leveraging technology to bring together a distributed international community. We looking forward to working together with all of you to identify the organizational, technical and community activities needed to advance OpenOceanCloud. The outcome of this brainstorming session will be published as a community whitepaper.
> 
> Login to GatherTown (link coming soon) at any point during the 44-hour event (15 Sepember, 00:00 pm CEST to 17 September, 08:00 pm CEST) to contribute to the white paper and see what other people have been working on. Moderators will be stationed in the discussion rooms throughout the event.
> 
> We welcome anyone and everyone interested in the future of ocean data infrastructure: researchers, industry professionals, government agency reps, environmental justice groups, and indigenous communities.
> 
> This brainstorming session is one of the Satellite Activities as part of the broader “A Predicted Ocean” UN Ocean Decade Laboratory event.
> 
> If we do want to update the site with any of this I am happy to make those edits.

**Comment by leslie-yoc** [comment]
I will get these edits into the website soon. I just want to make sure all the edits came through ok on the Partners page to make sure I am editing everything correctly (it looks a bit different from the Pangeo backend).

**Comment by leslie-yoc** [comment]
Updates have been added to the page and pull request has been requested.

**Comment by rabernat** [comment]
Closed by #13
